package com.mycompany.histomaplinkedlist;
import java.awt.GridLayout;
/**
 *
 * @author skyla
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }
    
    private void Graph(){
        String grades = MainWindow_TextField_Grades.getText();
        HistoMap histoMap = new HistoMap();
        String[] parts = grades.split(" ");
        for (String part : parts) {
            histoMap.put(Integer.parseInt(part));
        }
        
        //MainWindow_Panel_HashMap.setLayout(new GridLayout(10, 5));
        char[] letters = {'A', 'B', 'C', 'D', 'F'};
        
        int count = histoMap.get(letters[0]);
        MainWindow_Label_TextA.setText("A" + ": " + count);
        MainWindow_Label_TextB.setText("B" + ": " + histoMap.get(letters[1]));
        MainWindow_Label_TextC.setText("C" + ": " + histoMap.get(letters[2]));
        MainWindow_Label_TextD.setText("D" + ": " + histoMap.get(letters[3]));
        MainWindow_Label_TextF.setText("F" + ": " + histoMap.get(letters[4]));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindow_Button_GetHashMap = new javax.swing.JButton();
        MainWindow_TextField_Grades = new javax.swing.JTextField();
        MainWindow_Label_TextA = new javax.swing.JLabel();
        MainWindow_Label_TextB = new javax.swing.JLabel();
        MainWindow_Label_TextD = new javax.swing.JLabel();
        MainWindow_Label_TextF = new javax.swing.JLabel();
        MainWindow_Label_TextC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new GraphicsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainWindow_Button_GetHashMap.setText("Show HashMap");
        MainWindow_Button_GetHashMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_Button_GetHashMapActionPerformed(evt);
            }
        });

        MainWindow_TextField_Grades.setText("94 85 86 92 100 74 85 96 84 84 82 78 74 60 62 96 87 88");

        MainWindow_Label_TextA.setText("A");

        MainWindow_Label_TextB.setText("B");

        MainWindow_Label_TextD.setText("D");

        MainWindow_Label_TextF.setText("F");

        MainWindow_Label_TextC.setText("C");

        jLabel1.setText("<-Grades here");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MainWindow_Label_TextA)
                .addGap(131, 131, 131)
                .addComponent(MainWindow_Label_TextB)
                .addGap(124, 124, 124)
                .addComponent(MainWindow_Label_TextC)
                .addGap(128, 128, 128)
                .addComponent(MainWindow_Label_TextD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainWindow_Label_TextF)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainWindow_Button_GetHashMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_TextField_Grades, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MainWindow_Label_TextA)
                    .addComponent(MainWindow_Label_TextB)
                    .addComponent(MainWindow_Label_TextD)
                    .addComponent(MainWindow_Label_TextF)
                    .addComponent(MainWindow_Label_TextC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainWindow_Button_GetHashMap)
                    .addComponent(MainWindow_TextField_Grades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainWindow_Button_GetHashMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_Button_GetHashMapActionPerformed
    Graph();
    //passes the grade data to the Graphics Panel so that histogram is built in the GraphicsComponent(Graphics) methid.
    
    String data = MainWindow_TextField_Grades.getText();
    ((GraphicsPanel)jPanel1).processData(data);
    }//GEN-LAST:event_MainWindow_Button_GetHashMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainWindow_Button_GetHashMap;
    private javax.swing.JLabel MainWindow_Label_TextA;
    private javax.swing.JLabel MainWindow_Label_TextB;
    private javax.swing.JLabel MainWindow_Label_TextC;
    private javax.swing.JLabel MainWindow_Label_TextD;
    private javax.swing.JLabel MainWindow_Label_TextF;
    private javax.swing.JTextField MainWindow_TextField_Grades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
